import type { Metadata } from "next";
import ShopContextBascketProvider from "./context/shopContextBascket";

import "./globals.css";
import Navbar from "./components/Nabar";
import Layout from "./components/layout";
import { Fragment } from "react/jsx-runtime";


export const metadata: Metadata = {
  title: "M4Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <ShopContextBascketProvider>
        <Layout> {children} </Layout>
        </ShopContextBascketProvider>
          
        
                
      </body>
    </html>
  );
}
